# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n bgb
name: bgb
# in order of priority: lowest (top) to highest (bottom)
channels:
  - anaconda
dependencies:
  - click
  - cython
  - jupyter
  - matplotlib
  - openpyxl
  - pandas
  - pip
  - pytables
  - python=3
  - networkx
  - numpy
  - scipy
  - seaborn
  - scikit-image
  - scikit-learn
  - sqlalchemy
  - sympy
  - xlrd
  - pip:
    - dash
    - dash-renderer
    - dash-html-components
    - dash-core-components
    - msgpack
    - plotly
    - trueskill
